from fastapi import APIRouter

from app.api import (
    adhoc_dashboards,
    audit,
    auth,
    catalog,
    chat,
    checks,
    connections,
    contracts,
    custom_dashboards,
    dashboard,
    datasets,
    docs,
    exceptions_api,
    incidents,
    insights,
    knowledge,
    mcp,
    monitors,
    notifications,
    query,
    rca,
    runs,
    saved_queries,
    scorecards,
    search,
    sla,
    status,
)

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(catalog.router)
api_router.include_router(chat.router)
api_router.include_router(connections.router)
api_router.include_router(datasets.router)
api_router.include_router(monitors.router)
api_router.include_router(knowledge.router)
api_router.include_router(contracts.router)
api_router.include_router(checks.router)
api_router.include_router(runs.router)
api_router.include_router(exceptions_api.router)
api_router.include_router(incidents.router)
api_router.include_router(insights.router)
api_router.include_router(rca.router)
api_router.include_router(dashboard.router)
api_router.include_router(query.router)
api_router.include_router(saved_queries.router)
api_router.include_router(scorecards.router)
api_router.include_router(adhoc_dashboards.router)
api_router.include_router(custom_dashboards.router)
api_router.include_router(mcp.router)
api_router.include_router(notifications.router)
api_router.include_router(audit.router)
api_router.include_router(search.router)
api_router.include_router(sla.router)
api_router.include_router(status.router)
api_router.include_router(docs.router)
