"""schema snapshots

Revision ID: 0002_schema_snapshots
Revises: 0001_baseline
Create Date: 2026-06-16 05:57:20.241691

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002_schema_snapshots'
down_revision: str | None = '0001_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schema_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_schema_snap_dataset', ['dataset_id', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_schema_snapshots_dataset_id'), ['dataset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schema_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schema_snapshots_dataset_id'))
        batch_op.drop_index('ix_schema_snap_dataset')

    op.drop_table('schema_snapshots')
    # ### end Alembic commands ###
