"""sla tracking

Revision ID: 0003_sla_tracking
Revises: 0002_schema_snapshots
Create Date: 2026-06-16 06:13:55.517721

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0003_sla_tracking'
down_revision: str | None = '0002_schema_snapshots'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('objective', sa.Float(), nullable=False),
    sa.Column('window', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sla_definitions', schema=None) as batch_op:
        batch_op.create_index('ix_sla_enabled', ['enabled'], unique=False)

    op.create_table('sla_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sla_id', sa.Integer(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('attainment', sa.Float(), nullable=False),
    sa.Column('budget_consumed', sa.Float(), nullable=False),
    sa.Column('good', sa.Integer(), nullable=False),
    sa.Column('bad', sa.Integer(), nullable=False),
    sa.Column('breached', sa.Boolean(), nullable=False),
    sa.Column('mttr_seconds', sa.Integer(), nullable=True),
    sa.Column('mttd_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sla_id'], ['sla_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sla_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sla_evaluations_sla_id'), ['sla_id'], unique=False)
        batch_op.create_index('ix_slaeval_sla', ['sla_id', 'evaluated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sla_evaluations', schema=None) as batch_op:
        batch_op.drop_index('ix_slaeval_sla')
        batch_op.drop_index(batch_op.f('ix_sla_evaluations_sla_id'))

    op.drop_table('sla_evaluations')
    with op.batch_alter_table('sla_definitions', schema=None) as batch_op:
        batch_op.drop_index('ix_sla_enabled')

    op.drop_table('sla_definitions')
    # ### end Alembic commands ###
